### ISSUE TITLE
Each apt upgrade tries to reinstall removed (default) packages

### ISSUE THREAD

**Issue by tekaeren** [pop-os/shop#194]
Distribution (run cat /etc/os-release):
Pop!_OS 20.04 LTS

Related Application and/or Package Version (run apt policy $PACKAGE NAME):
probably Pop Shop 3.3.0pop0~1589405854~20.04~72b0ae9

Description:
I'm using Pop!_OS on non System76 hardware. So I do not need some kernel modules provided by default installation. 
I tend to use newest kernel available, and not the supported LTS one.
Some applications istalled by default have no use for me and I want to remove them permamently.

I remove unneeded stuff, but each time with another apt-get upgrade, the packages want to be installed again.

Steps to reproduce:
Issue `apt purge eog geary gnome-terminal gnome-terminal-data intel-microcode iucode-tool linux-generic linux-headers-generic linux-system76 nautilus-extension-gnome-terminal pop-desktop thermald`.

And with `apt update && apt dist-upgrade` I get each time:

`~# apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed
  eog geary gnome-terminal gnome-terminal-data intel-microcode iucode-tool linux-generic
  linux-headers-generic linux-image-generic linux-system76 nautilus-extension-gnome-terminal pop-desktop thermald
0 to upgrade, 18 to newly install, 0 to remove and 0 not to upgrade.
Need to get 78,3 MB/81,6 MB of archives.
After this operation, 378 MB of additional disk space will be used.
Do you want to continue? [Y/n]`

Expected behavior:
Do not force (re)install removed packages.

**Comment by TechnologyMan101** [comment]
I notice how you are using `dist-upgrade`. I use `full-upgrade` which is recommended by System76 anyways. I don't have this problem even though I ALWAYS remove Geary on every install.

**Comment by jacobgkau** [comment]
> I notice how you are using `dist-upgrade`. I use `full-upgrade` which is recommended by System76 anyways.

`dist-upgrade` and `full-upgrade` are synonyms; apt runs the same code for either one. (Technically, `dist-upgrade` is deprecated and `full-upgrade` is the newer term.)

> I tend to use newest kernel available, and not the supported LTS one.

At this time, Pop!_OS doesn't use LTS kernels. We typically try to follow mainline while still going through our QA processes. See https://github.com/pop-os/linux.

---

This issue is referring to `apt` and doesn't concern the Pop!_Shop frontend. Furthermore, it's actually taking an issue with how packages are/were marked within the distribution. There have been several efforts in https://github.com/pop-os/desktop to reduce the number of required dependencies and also to move important but manually-removable packages from "essential" (which get auto-reinstalled) to "protected" (which do not).

I'm going to go ahead and close this; please open an issue in https://github.com/pop-os/desktop if you still find the behavior unsatisfactory on an up-to-date 22.04 LTS installation.
