### ISSUE TITLE
Support for paid apps?

### ISSUE THREAD

**Issue by marbetschar** [pop-os/shop#196]
Hi there,

I just installed Pop!_OS to give it a test drive and coming from elementary, I was pleased to see you are using AppCenter too :)

So I tried to install some elementary apps such as [Ideogram of Cassidy](https://appcenter.elementary.io/com.github.cassidyjames.ideogram/). Unfortunately I'm not able to, because it seems Pop!_Shop [is compiled with payments disabled](https://github.com/pop-os/shop/blob/72b0ae9e0ee85e8c07acb8874149e6fdaa5b8fe6/meson_options.txt#L6) (ignoring potential compatibility issues here).

As I'm developing some apps too, this brings me to my question: Will Pop!_OS enable paid apps and allow developers to submit apps to the Pop!_Shop?

**Comment by cassidyjames** [comment]
For context, we (elementary) are working with Flathub and Flatpak folks on getting payments supported in Flatpak itself. At that point, any apps that request payment will do so regardless of the app store being used. I can't comment on the ability to submit apps to Pop!_Shop with any authority (since I don't know their plans), but I kind of doubt it; I presume the path forward is leaning on Flathub since they include that ootb in Pop!_OS now.

Note that adding the AppCenter debian repository on anything other than elementary OS is completely unsupported.

**Comment by marbetschar** [comment]
> For context, we (elementary) are working with Flathub and Flatpak folks on getting payments supported in Flatpak itself. At that point, any Flatpak apps (whether from the AppCenter remote or Flathub) that request payment will do so regardless of the app store being used.

That's great news!

> I can't comment on the ability to submit apps to Pop!_Shop with any authority (since I don't know their plans), but I kind of doubt it; I presume the path forward is leaning on Flathub since they include that ootb in Pop!_OS now.

Given the context, this makes total sense.

> Note that adding the AppCenter debian repository on anything other than elementary OS is completely unsupported.

Sure thing, did not expect it to work at all but tested it nevertheless and got curious as I came across the payment not supported hint :)

Closing the issue for now...
