### ISSUE TITLE
Support Snap Packages

### ISSUE THREAD

**Issue by atrauzzi** [pop-os/shop#235]
I realize that popos has placed a bet on flatpack, but snap is still doing well and it doesn't help me to have to install two applications to manage my system's dependencies and automatic updating.

Is there any reason why the pop shop couldn't just be expanded to support snap (on top of flatpack and deb)?  It would make my life a lot easier to be able to consume packages from both.  I do get the sense that snap is doing well and does seem to offer more first-party-distributed applications rather than the many third party wrappers that I see on flatpack.

**Comment by leviport** [comment]
Thank you for the feedback. At this time, we are not looking at including snap support in Pop!_Shop, however snap can still be used via the command line or by installing the Ubuntu snap store.

**Comment by atrauzzi** [comment]
You should really revisit that. There are considerably more first party snaps for many common applications than flatpaks. Moreover, snaps appear to be superior at offering a better install experience and interoperability.

It would serve your user base well to not try and be restrictive about this. Especially so that updates can be handled from one spot.

Also, the popos default theme currently breaks the snap store, so your response is at least currently, a bit disingenuous. At least if you're trying to use it as a way to sound open.

**Comment by leviport** [comment]
> Also, the popos default theme currently breaks the snap store, so your response is at least currently, a bit disingenuous. 

It was not intended to be disingenuous, my apologies if it came across that way. Since we don't package the snap store by default, I have not done much testing with it and I was unaware of that bug. If the theme is the issue, we'd love to see a bug report filed [in the theme repo](https://github.com/pop-os/gtk-theme/issues). It is not our intention to discourage, restrict, or otherwise persuade people to use or not use snaps. We just aren't looking to add them to Pop!_Shop at this time.

**Comment by atrauzzi** [comment]
Why not?

**Comment by isantop** [comment]
The problem is that the Snap store has entirely custom theming which isn't shipped as CSS with the store. It's therefore broken on anything that isn't using the Yaru theme. The correct place that needs to be fixed is in the Snap Store, not in the theme. 

We evaluated both Flatpak and Snap and Flatpak was found to be a better option for our users. This decision remains the correct choice for our users. Snap is easily available to install from the Pop OS repos; if that's not sufficient, then a different OS that does provide snap by default would be a better choice.

**Comment by atrauzzi** [comment]
What criteria do you use to define "better"? I'm genuinely curious.

**Comment by PixsaOJ** [comment]
Somebody just has to release themes for snap. I am using Layan theme and it's beautiful. There are other themes too. Why does Pop!_Shop care about app themes? It would be cool if we had basic functionality like: searching, installing, uninstalling, checking for updates (just run `snap refresh`).

On top of that, If themes are the problem, that's not hard either. Honestly, theming functionality does not belong in app store.

**Comment by PixsaOJ** [comment]
```
snap install pop-themes

for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:gtk-3-themes; done

for i in $(snap connections | grep gtk-common-themes:gtk-2-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:gtk-2-themes; done

for i in $(snap connections | grep gtk-common-themes:icon-themes | awk '{print $2}'); do sudo snap connect $i pop-themes:icon-themes; done
```

**Comment by qaqak** [comment]
Why does the theme matter when it comes to adding Snapcraft.io as a source to the Pop!_Shop? The same way you did it for Flatpak, do it for Snap!

**Comment by oVerde** [comment]
+1 to the snapcraft as a source at the Pop_Shop

**Comment by dave-kennedy** [comment]
> We evaluated both Flatpak and Snap and Flatpak was found to be a better option for our users.

I know it's bad form to comment on a close issue (and most likely pointless) but I'm also genuinely curious. I read somewhere that the security model of Flatpak is better in theory because a malicious app will have limited access. However, there are plenty of Flatpaks that ship with `device=all` and/or `filesystems=host`, including GIMP, IntelliJ and Touche to name a few. The app store doesn't surface this info, so I assume many users install and run these things without thinking twice about their permissions.

I'm not convinced Flatpak is better or worse than Snap, for what it's worth, but sometimes Snap is the only officially supported alternative to downloading a tarball from a website.
