### ISSUE TITLE
Pop!_Shop shows daemon as an app.

### ISSUE THREAD

**Issue by vega-d** [pop-os/shop#241]
**Distribution:**
```
 NAME="Pop!_OS"
 VERSION="20.10"
```
 
 
**Related Application and/or Package Version:**
```
syncthing:
  Version table:
 *** 1.10.0~ds1-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Syncthing package doesn't provide UI and essentially not an app but a daemon. 
Yet pop shop shows it as an app and it has AppStream data for it.
![](https://i.imgur.com/ufudwnm.png)

**Steps to reproduce:**
- open pop!_shop
- search for `syncthing`

**Expected behavior:**
syncthing daemon should not appear as an app

**Comment by jacobgkau** [comment]
At this time, I have three search results for Syncthing in the Pop!_Shop:

![Screenshot from 2023-10-09 12-04-07](https://github.com/pop-os/shop/assets/7199422/f1b70de1-265b-46b6-a774-d201cdde88a4)

Syncthing Web UI, which looks like the closest equivalent to what's in your screenshot, installs two .desktop files, one of which is titled Start Syncthing:

![Screenshot from 2023-10-09 12-04-38](https://github.com/pop-os/shop/assets/7199422/a9e39609-2659-425a-b5a5-a122e8e54e76)

Running Start Syncthing and then Syncthing Web UI does work to access the Syncthing GUI. (Running Syncthing Web UI without first running Start Syncthing opens a web browser but displays an error page since Syncthing isn't running.)

This setup is a little clumsy, but it does appear to work. Furthermore, Pop!_OS is not the packager for these Syncthing packages, and the shop is just displaying the AppStream data that's being provided to it by, in this case, Ubuntu (see `apt policy syncthing`).
