### ISSUE TITLE
io.elementary.appcenter is eating a lot of memory

### ISSUE THREAD

**Issue by mancarv** [pop-os/shop#257]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
io.elementary.appcenter

**Issue/Bug Description:**
![image](https://user-images.githubusercontent.com/18390009/107384021-94a3e980-6abf-11eb-86ca-8f26059f446d.png)
This process is consuming 800mb! This is a lot of RAM that I need for other purposes. When I hit the 90% memory used mark then the system start to lagging.

**Expected behavior:**
I believe max ~200mb ram is a good amount of memory for a process running in the background, that's because I have 16gb of ram, maybe someone with 4gb thinks different.

**Other Notes:**
My laptop is an Acer E-431 with i5-3230m and 16gb ram DDR3

**Comment by ids1024** [comment]
Hm, it does seem to be an issue:

![Screenshot from 2021-02-09 08-50-40](https://user-images.githubusercontent.com/2263150/107397899-f0687580-6ab3-11eb-9bc4-f56722f6135d.png)

This is on a computer that hasn't been rebooted in a while, so perhaps it's leaking memory the longer it runs. Killing the process and running it again brings it to 423 MiB.

**Comment by ids1024** [comment]
Related upstream issues: https://github.com/elementary/appcenter/issues/494, https://github.com/elementary/appcenter/issues/1170

**Comment by mancarv** [comment]
So... It's related to elementary and we have to wait for them to resolve it? elementary#494 is tagged "Priotity high" since 2017 but nobody is assigned and doesn't give a lot of hope... 

Kill the process (when I need this memory) won't affect the OS? I can live killing it when it bothers me but I concerned that could affect anything else..

**Comment by cassidyjames** [comment]
Upstream has been addressing memory usage regularly over the past several years; @davidmhewitt might be able clarify, but I honestly think the old issues should be closed without any new information. It's just hard to close a vague issue that's like "x is using a lot of memory" when we've been consistently addressing memory usage little by little.

**Comment by mancarv** [comment]
OK, I'll have the OS updated and will come back in a week or so to report how it is going. I'm gonna test keeping the laptop on at least 48h before next report.

**Comment by mancarv** [comment]
Well, I have updated my OS almost daily but my uptime right now is 7 seven days. So I suppose that I should restart to test properly... At the moment the process is consuming almost 1GB
![image](https://user-images.githubusercontent.com/18390009/108141577-010b8380-7092-11eb-941a-05f27a9e7410.png)

I'm gonna turn it off tonight, I'll come back in few days to report the memory usage.

**Comment by gp-97** [comment]
Even in my case, Pop_Shop is eating a lot of memory and that too when I am using it normally

**Comment by cassidyjames** [comment]
Pop!_Shop has not been rebased off of upstream changes over the last several months. See #217 and #258.

**Comment by mancarv** [comment]
We can just wait for the rebase and hope it really fix it

**Comment by mancarv** [comment]
Well, last week I noticed the OS was a little bit different, so I checked and finally the rebase was done! This is the result after 88h of uptime! For me its working better than on February. Maybe 500mb of RAM is a lot of memory for other users but it looks good to me now. Should I close the issue?
![image](https://user-images.githubusercontent.com/18390009/115184822-3b020180-a0a4-11eb-8b59-d43f7400a495.png)

**Comment by mancarv** [comment]
This is after 11 days, to me it's not an issue anymore. I believe in the future is going to improve because they still watching this in elementary#1507 

@ids1024 @mmstick and @cassidyjames thanks for your work.

![image](https://user-images.githubusercontent.com/18390009/116082358-edb40000-a660-11eb-99ba-38f1197742bb.png)

**Comment by hholst80** [comment]
Why is this closed? This is as bad and unaddressed as it was 1.5 years ago.
If you cannot fix it remove it. It degrades the OS to Windows 95 Early-access standards. 

![Screenshot from 2022-09-16 20-17-20](https://user-images.githubusercontent.com/6200749/190707610-28328921-be4c-4633-9d47-ed38fe6159c3.png)

**Comment by leviport** [comment]
@hholst80 the reasoning for it being closed was clearly explained in this very thread, and I'm getting results that match the original poster's before closing the issue. 

> If you cannot fix it remove it.

You are welcome to do so (`sudo apt remove pop-shop`), but we are not going to do so by default on all Pop installations. That would leave users without a software center.

**Comment by hholst80** [comment]
Why does it run as a daemon when you are aware of this severe resource over use problem? It can start and terminate on request. There is no need to fry users laptops for no good reason I think?

**Comment by leviport** [comment]
It runs as a daemon because it notifies users when updates are available.

>when you are aware of this severe resource over use problem?

That's a little hyperbolic, seeing as how myself and the OP are both seeing ~500mb RAM usage by Pop Shop.

>There is no need to fry users laptops for no good reason I think?

And that's _very_ hyperbolic. Pop Shop running in the background is not going to fry anyone's laptop. I don't appreciate that accusation, and I ask you to please tone down the rhetoric.

**Comment by t-lock** [comment]
@leviport Epic calm. Love your style.

**Comment by hholst80** [comment]
I'd gladly "tune down my rethoric" if you tune up your ambitions.

Say there is 10K installations of PopOS! out there. Each of them running this application to be notified in the eventuality of an update to an application installed through it. (Like how many will have that? 10%??). Let us suppose it "only" uses 500MB on average. That still adds up to 5 TERABYTE of RAM to keep 10K clients ajour on any eventual updates to application. Since the client only needs to run *if* there is a software package installed you can just spawn that client on demand.

It is possible to run a *single* MQTT message broker that uses 1 GB to handle those clients and notify them with a pubsub push if the software should to be updated. The pubsub notification client can spawn the 500 MB "software center" blob on demand. Or just use dbus notify as everyone else is. Just how small can the client get? There are MQTT clients running on 100 KB of memory consumption without breaking a sweat. 

With this simple redesign the total energy consumption goes down from 5 TiB + your current server overhead to only 2 GB of *total system* memory consumption. Most likely it will be much less if the client is optionally started as described above.

You are reinventing the wheel and quite frankly not doing a very good job. I want you to be aware of that and not be delusional in thinking that it is reasonable for a notification client (daemon) to consume this much memory.

**Comment by leviport** [comment]
The sum of all of the RAM used by all users of Pop is not a meaningful metric in any regard, and I'm not sure why you felt the need to bring it up. But at least trimming down RAM usage is a more reasonable position than claiming that the Pop Shop is going to "fry" users' laptops.

You want a slimmer upgrade notifier daemon? Cool, sounds like a great idea, and we love community contributions. You think the way to manifest a slimmer upgrade notifier daemon is to jump into a closed issue and berate the developers? Do you think that is reasonable or productive?

If you were entering the discussion with civility, I'd be happy to tell you that we've begun to take steps to [keep Pop Shop from running in the background](https://github.com/pop-os/shop/pull/390) constantly, and that I was mistaken about the Shop being needed for update notifications since [the Pop System Updater](https://github.com/pop-os/system-updater) was rolled out. 

But since civility seems to be too much to ask, I'm going to remind you that there is a [Code of Conduct](https://github.com/pop-os/code-of-conduct), and warn you that if you breach it one more time, I will block you from all Pop!\_OS repos.

**Comment by hholst80** [comment]
"Warn me", ban me all you want but for the sake of the users you still have fix the issue. Don't waste your time trying to debate the problem away.

**Comment by mancarv** [comment]
@hholst80 please make a new issue about what you are complaining, my issue is closed

**Comment by leviport** [comment]
>but for the sake of the users you still have fix the issue

You must have skipped over the third paragraph in my post that mentions that we are working on it. You're being confrontational for absolutely no reason. I've locked this issue since this conversation has become unbearably tedious. My warning about further breaches of the Code of Conduct still stands. I don't want to ban anyone who wants to participate, but you have to be respectful.
