### ISSUE TITLE
Support system-wide Flatpak remotes

### ISSUE THREAD

**Issue by locness3** [pop-os/shop#261]
The ability to use software from system-wide Flatpak remotes has been added in elementary AppCenter in https://github.com/elementary/appcenter/pull/1308. Would be nice, IMO, to have this here as well.

**Comment by jacobgkau** [comment]
This is present in current versions; it's actually been supported since April 2021 (https://github.com/pop-os/shop/pull/258 & https://github.com/pop-os/shop/pull/217).

Note that we only install the user-level repo by default in Pop!_OS, so you need to add the system-level repo manually. After that, next time Pop!_Shop is started fresh (may require killing the process or rebooting to kill the process), you'll have an additional dropdown for a system-wide installation.

![image](https://github.com/pop-os/shop/assets/7199422/52c50a2c-a4cc-4044-bb8f-e4f70b9d99a5)
