### ISSUE TITLE
Sushi not available in Pop Shop

### ISSUE THREAD

**Issue by titojankowski** [pop-os/shop#288]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-sushi

**Issue/Bug Description:**
The "push space to preview a file" function in macOS Finder is useful especially for scanning pictures.

Although this isn't in Pop OS/Nautilus, an app named Sushi can add it. But Sushi isn't available in the Pop Shop. Seems like one of those basic utilities that should be readily available (even better just included by default or in a settings menu)

**Steps to reproduce (if you know):**
Search Pop Shop for sushi, no results

**Expected behavior:**
Sushi available to install

**Comment by rvente** [comment]
I think the package name is `gnome-sushi` but I can't be sure because I'm running 20.04. Are you using this in Nautilus (the file manager)? Using Nautilus for me pressing space has worked for me. I don't know if I even needed to manually install it, but doing so is simple as `sudo apt install gnome-sushi` in terminal. 

Many packages are installable but they are small utilities or don't have an "application" presence, so they don't show up in Pop Shop.

**Comment by rvente** [comment]
I just downloaded `pop-os_21.04_amd64_nvidia_9.iso` and I'm unable to reproduce that behavior. Without further prompting, after `sudo apt install gnome-sushi`, I switched over to Files and could press the spacebar to invoke preview.

If you haven't already, perhaps try doing a `sudo apt update && sudo apt upgrade`. Next, install `gnome-sushi` again. Finally, you can report your status after a reboot. From what I can tell, your Nautilus could be a little out of sync with the version of Sushi you have installed. Otherwise, off a fresh ISO, installing it just works. If it still doesn't work, try a modification of a command I found here: <https://stackoverflow.com/a/34889945> and change  `yourusername` and `yourfile` to something you want to preview. For example.

`echo "Hello" > ~/yourfile.txt`

```
dbus-send --print-reply --dest=org.gnome.NautilusPreviewer /org/gnome/NautilusPreviewer org.gnome.NautilusPreviewer.ShowFile string:"file:///home/yourusername/yourfile.txt" int32:0 boolean:false
method return time=1633672019.268934 sender=:1.753 -> destination=:1.754 serial=25 reply_serial=2
```
With that error message, we'll be able to debug the issue.

**Comment by rvente** [comment]
I see, so you have been able to install it, then? If so, great. I'm far from an authority on how things are listed in the Pop Shop (just a user trying to lend a hand) - I think it might even be something a community member can add to the repos. This issue can stay open until we get more info on packages being added to the default options.

**Comment by titojankowski** [comment]
> Easiest way to install Sushi(it works in both 21.04 & 21.10)
> 
> * Right click Files app in Applications view & click Show details, which will open it in pop shop.
> * Then scroll down to listed extensions for Files & then install Sushi from there.
> 
> Edit: To keep it simple, it is available in Pop Shop, not as an application but as an extension for Files(nautilus) app.

Oh wow never noticed this function in the Pop Shop before. Thanks!

Should Extensions show up in search results?

**Comment by senntore** [comment]
> Perhaps should Extensions show up in search results?

Not currently, though it would be nice to have them in search results.

**Comment by titojankowski** [comment]
Well then that's a pretty different issue "Nautilus extensions should show up in Pop Shop results". Not really a bug though, more of a usability question. I'm gonna close this for now, @senntore feel free to create a follow up.
