### ISSUE TITLE
MIssing german translation on button in archive settings

### ISSUE THREAD

**Issue by yfons** [pop-os/shop#294]
**Distribution :**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
latest pop Shop idk the package name

**Issue/Bug Description:**
![Bildschirmfoto vom 2021-10-12 12-25-19](https://user-images.githubusercontent.com/84090601/137188677-aee5bdef-20cf-4e5d-9ab0-60ddf3a8ef2e.png)
the "Open in Pop Shop" Button isnt translated at all, i have the german pop os versionand everything is translated except that button

ive ran that and no errors occured at all, so the translation is probably correctly installed just the button is not translated

sudo apt clean | tee -a ~/updates.txt

sudo apt update -m | tee -a ~/updates.txt

sudo dpkg --configure -a | tee -a ~/updates.txt

sudo apt install -f | tee -a ~/updates.txt

sudo apt full-upgrade | tee -a ~/updates.txt

sudo apt autoremove --purge | tee -a ~/updates.txt

sudo apt install pop-desktop gdm3 | tee -a ~/updates.txt 

**Steps to reproduce (if you know):**
just start latest pop shop on a german version of pop... probably other languages are also affected

**Expected behavior:**
it should be  "Öffnen in Pop-Shop" and not "open in pop-shop"

**Other Notes:**

**Comment by jacobgkau** [comment]
That button doesn't seem to be present anymore in the current version of Pop!_OS:

![Screenshot from 2023-10-09 12-10-53](https://github.com/pop-os/shop/assets/7199422/aaa55809-994c-4bc9-b56d-a9e2be584a8c)

Looking at https://github.com/pop-os/gnome-control-center/tree/master_jammy/debian/patches, the patch that originally set that button up in https://github.com/pop-os/gnome-control-center/pull/18 is no longer there.

I'm closing this issue since it's no longer relevant, but if it comes back, the appropriate repository would be https://github.com/pop-os/gnome-control-center since that's the app where the button is located.
