### ISSUE TITLE
Pop!_Shop package install error message not helpful to average users

### ISSUE THREAD

**Issue by qwertychouskie** [pop-os/shop#296]
Currently, the error given by the Pop Shop when a package is unable to be installed doesn't give any pointers how to actually resolve the issue.  Perhaps add this to the dialog after the existing part:

```
Try the following to resolve this error:

- Make sure you are connected to the Internet
- Install all available updates via the Installed tab of the Pop!_Shop, reboot your computer, and try again
- If the software supports multiple installation types, use the drop-down next to the Install button to select a different option and try again

If you still encounter this error, check out our friendly support! https://support.system76.com
```

This issue came up in first part of LinusTechTips's Linux gaming challenge, and the lack of guidance resulted in the brand new install quickly getting bricked.  The issue would have most likely been avoided if there was more guidance in place (e.g. to try the Flatpak version).  As this video is currently only on Floatplane and not yet published to YouTube, I have attached the relevant excerpt: https://user-images.githubusercontent.com/13989090/138944524-512d9997-a1de-45cb-b141-b7aaa2462daa.mp4

(Also, I should point out he's not the only one who ran into this issue: [example 1](https://www.reddit.com/r/pop_os/comments/q9xq3y/why_does_installing_steam_from_apt_make_me/ ) | [example 2](https://github.com/pop-os/pop/issues/1958))

**Comment by 13r0ck** [comment]
## Old
![shop_old](https://user-images.githubusercontent.com/58987761/140798900-a963ceff-497b-4376-93e1-d50793c9839f.png) 
## New
![shop_new](https://user-images.githubusercontent.com/58987761/140798921-66fc002f-55bf-4752-801b-b032b34597f0.png)

This doesn't yet support translations, looking for input on text and layout @pop-os/quality-assurance ?

**Comment by 13r0ck** [comment]
Maybe there should be a `Install Updates` button next to the `Close` button? That closes the error window and takes the user to the updates tab?

**Comment by jacobgkau** [comment]
I think the suggested messaging from @qwertychouskie looks better than what's in that screenshot currently. Namely, `Installed tab` is uppercase since it's referring to the tab by its name (proper noun), refers to `this error` instead of the vaguer `the error`, I'm not sure we would call the sources drop-down an "install button drop-down," etc.

Adding periods to the end of the bullet-points is fine. Suggesting to reboot probably isn't necessary for packaging issues, but probably wouldn't hurt either.

```
Try the following to resolve this error:

- Install all available updates via the Installed tab of the Pop!_Shop, reboot, and try again.
- If the software supports multiple installation types, use the drop-down next to the Install button to select a different option and try again.
```

> Maybe there should be a `Install Updates` button next to the `Close` button? That closes the error window and takes the user to the updates tab?

If we're going that far, I would think having the Pop!_Shop automatically install updates first when the `Install` button is used would be a more straightforward approach.

**Comment by qwertychouskie** [comment]
I updated the wording in the original post to include the bit about rebooting and a couple small tweaks.  IMHO, the reference to support.system76.com should definitely be included (clickable link if possible would be great).

**Comment by titojankowski** [comment]
The expanded text is more helpful. When you say "Install all available updates" do you mean users should click the "Update All" button on "Installed"?

That said as a fairly new user I can't promise I would read the error given the red error logo and the only button being "Close". I like the idea of another button because it gives me something to do rather than just "Close". The button doesn't need to be powerful, it could just take me to the "Installed" tab for example, and I would need to click "Update All" myself.

**Comment by 13r0ck** [comment]
@titojankowski 
Adding an `Install Updates` button to the error (and other similar errors) is already in the works [here](https://github.com/pop-os/shop/issues/296#issuecomment-963473959).

**Comment by 13r0ck** [comment]
What do you all think? Also @maria-komarova 

https://user-images.githubusercontent.com/58987761/141175845-52a805cf-f857-48f0-8abe-b40c076bb211.mp4

> I know the error message here is because of network failure, that was just to make the issue easier to reproduce during development.

**Comment by qwertychouskie** [comment]
Looking good!  I just updated the message one more time to mention making sure you are connected to the Internet.  (Also, is it easily possible to put in the hyperlink to the support site like in my first post?)

**Comment by titojankowski** [comment]
@13r0ck since you were able to re-create this error by turning your network off, perhaps the new error message should address that? Or how is no network connection handled?

On the macOS App Store for example, when disconnected from the internet pressing "Update" on an app does nothing.

**Comment by 13r0ck** [comment]
@titojankowski 
Please read [this](https://github.com/pop-os/shop/pull/302#issuecomment-965885876). This has already been discussed.
