### ISSUE TITLE
Search for installed packages doesn't work

### ISSUE THREAD

**Issue by lucamosca1** [pop-os/shop#321]
Environment: Pop!_OS 21.10, fully upgraded, italian localization

If I open Pop Shop, go to Installed tab and try to search something, Search field is not clickable and I can not search anything

![Schermata del 2022-01-09 11-01-32](https://user-images.githubusercontent.com/5502068/148677767-fa6ecf47-f29d-4008-a217-d26a4126905f.png)

**Comment by isantop** [comment]
This is intended behavior, because it's unclear to the user what would be searched in such a position. Generally the search applied to the current view, so opening the Audio category only searches within the Audio category. However, in the installed view, it's not clear whether the search would look through all applications, or only within the currently-installed applications.

**Comment by cassidyjames** [comment]
See also: https://github.com/elementary/appcenter/issues/493 for related discussion

**Comment by lucamosca1** [comment]
Ehm ... ok, but if not used ... isn't better to hide it :)

my 2 cents
