### ISSUE TITLE
Pop Shop completely empty

### ISSUE THREAD

**Issue by pythongiant** [pop-os/shop#33]
![screenshot from 2017-12-02 21-20-53](https://user-images.githubusercontent.com/13624560/33517251-bc1d710c-d7a6-11e7-922a-b3ac770fde02.png)
This screen comes up at every tab i open in The shop

**Comment by mrlinnth** [comment]
Yes same here.
I thought it was only the issue when I was testing on bad internet.

After installing it today, it was still the same.

**Comment by isantop** [comment]
What settings do you have selected in the `Software & Updates` application?

**Comment by WatchMkr** [comment]
@isantop I've seen many similar reports. This seems to occur after a new install. After running updates once, the store is populated.

**Comment by NewEve** [comment]
@isantop @WatchMkr New install, ran updates, `apt-get update` & `upgrade`--still nothing, the shop isn't populated.

I had a small update via the shop and some software show up like Firefox or Steam but that's it.

That being said, the "Canonical Partners" repositories isn't ticked in "Other software" (see last picture)--and this doesn't seem normal to me but I'm not 100% sure. I cannot tick it nor know with what content to edit it...

Any ideas how I could help you help me :) ?

Everything otherwise runs like a dream...

![popshopaccessories](https://user-images.githubusercontent.com/29798378/36389656-2d723572-15a0-11e8-8bd2-7d85b0fc4076.png)

![popshopgames](https://user-images.githubusercontent.com/29798378/36389660-31ed2274-15a0-11e8-8826-2e2055a97cb1.png)

![popshopupdates](https://user-images.githubusercontent.com/29798378/36389661-366ccf52-15a0-11e8-937c-822bb0a127e9.png)

![software updates](https://user-images.githubusercontent.com/29798378/36389665-397133f0-15a0-11e8-8499-ad2d17756430.png)

![software updatesother](https://user-images.githubusercontent.com/29798378/36389674-3c8a11c4-15a0-11e8-841e-745001ae4248.png)

**Comment by isantop** [comment]
Enabling the Partner repo doesn't actually fix this issue, it just triggers a cache refresh (which does). You can effect the same result by running `sudo apt update` in a terminal.

**Comment by NewEve** [comment]
That's the thing I don't understand: I did run `sudo apt-get update`, although I forgot to mention the `sudo` above (now corrected).
I ran this more than once in the terminal, as well as rebooted--to no avail.
Is it a question of `apt-get` versus `apt`?
