### ISSUE TITLE
Pop Shop display issues with Pop OS high contrast theme

### ISSUE THREAD

**Issue by mbentham** [pop-os/shop#360]
**Distribution:** Pop!_OS 22.04 
**Related Application and/or Package Version:** 3.4.2pop0\~1655124030\~22.04\~3c67714
**Issue/Bug Description:**
When viewing an application page in pop shop and using the high contrast theme the Source drop down menu, install/uninstall button and space requirements are barely visible:

![image](https://user-images.githubusercontent.com/80548065/173514717-a7ca7fe0-bee3-46fb-840d-c4d9fc7f030a.png)

**Steps to reproduce** 

Switch to high contrast theme in pop os settings, open shop, click on any application

**Expected behavior:**

Buttons and text should be clearly visible, like in the default theme:

![image](https://user-images.githubusercontent.com/80548065/173514971-53e2119e-28cf-4f6e-91b9-17e4be0728d2.png)

**Other Notes:**

This also seems affects most other light-background GTK themes

**Comment by witepskas** [comment]
Hello. I'm interested about this  ....... I have the same issue or bug or... Someone said "closed this as completed in #361" but why i still have this bug? Can someone explain me how to fix this thing? Shouldn't be there an update related to this bug? I could edit these files, because i know css and a little bit more, but... i'm just linux user (and i really like it, last year pop os is my favorite distro (finaly i found it after many years with kubuntu)), so there should be some update or smthg else simple to fix that...or someone could tell me which files to edit... sorry for my english and long text :)
