### ISSUE TITLE
Feature request: Disable certain updates

### ISSUE THREAD

**Issue by zoliidev** [pop-os/shop#417]
I got some issues with the Nvidia driver, so i had to purge the apt packages to install directly from their site.
Now the PopShop always wants me to install the Nvidia drivers which breaks my system.

![image](https://github.com/pop-os/shop/assets/42400694/88906371-7c70-4a54-943c-c83eb1561cac)

So my request is to enable users to disable updates from packages.

**Comment by leviport** [comment]
The UX on that is a bit weird, but the "Install" button is not meant to indicate that it wants you to install it, but rather that it's available for install. Updating won't install it unless some other package has it as a dependency, which is more of an apt thing than a pop-shop thing. When updates are available, you'll see an "Update" button rather than an "Install" button.
