### ISSUE TITLE
Unable to group applications on Gnome Dash

### ISSUE THREAD

**Issue by dragonbite** [pop-os/shop#47]
Version: Pop! OS 17.10 (just downloaded and installed yesterday)

Generic Gnome Software allows listing installed applications that can be selected and then grouped. By default System Utilities and LibreOffice are grouped.

Pop!_Shop doesn't include an option for listing and selecting installed software to do the same. 

If it does include this, it is not obvious so maybe a button needs to be included along the top like it is in the Gnome Software package.

**Comment by isantop** [comment]
Thanks for your question! We actually feel that application group/folder management should take place in the shell rather than in the store, and we're looking at ways to implement this there. Possibilities include using an extension or adding drag functionality to the app wall (similar to iOS and Android).
