### ISSUE TITLE
Pop Shop won't load if NetworkManager is stopped

### ISSUE THREAD

**Issue by selfhostedfun** [pop-os/shop#83]
**Distribution (run `cat /etc/os-release`):**
 ```
byteme@hellmouth:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
byteme@hellmouth:~$ apt policy pop-shop
pop-shop:
  Installed: 0.2.9~1526005515~18.04~18df10f
  Candidate: 0.2.9~1526005515~18.04~18df10f
  Version table:
 *** 0.2.9~1526005515~18.04~18df10f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Was doing some home network changes and wicd was easier to quickly pick specific wifi channels/frequencies. Stopped NetworkManager, started wicd and successfully connected to my wifi. 

When loading Shop with my network managed by wicd, Shop will continuously just report the network is down. 

**Steps to reproduce (if you know):**

Stop NetworkManager. Use wicd (or another tool, possibly) to setup wifi. 

**Expected behavior:**

Pop Shop shouldn't have a hard check for NetworkManager.

**Other Notes:**

**Comment by cassidyjames** [comment]
Upstream comment:

>I think I'm going to close this issue as "Out of Scope" as it's not inside the scope of AppCenter to manage networks. That's why we have services like NetworkManager is to make sure we aren't implementing the same code in our apps and we have a canonical source of truth for things like network status. I think it's reasonable to expect that the system networking service is running.

**Comment by mutech** [comment]
If it is out of scope for App-Center to manage networks (I fully agree with this), it should not try to do it.

The problem is that network-manager is not *the* authority for determining whether there is a network connection, even if there might be an API that offers this functionality. Why? Because it doesn't actually do that, it checks if there is a network-manager connection, not a network connection.

Consequently, the well meaning attempt to check for a network before offering network functionality utterly fails here, in that an important functionality (software updates and installing new software) is unavailable, even though there is a perfectly working network connection.

That's really bad, especially if updates or update-notifications are actually affected by this (not sure, didn't check it yet).

There is also no good or at least not obvious solution to that. I personally have a good reason to configure my cabled network setup using systemd-networkd and my Wifi using network-manager. If I had to choose between not using network-manager and not using Pop-OS as a workstation system, Pop-OS would loose, because what I really want from Pop-OS (Cosmic), I can get from other Linux distros with a little effort, but network-manager used for this purpose is a constant source of problems in my particular situation, so this is not something I'm willing to use.

On the other hand, what would be the problem in keeping the functionality of checking (and failing to discover a network) with network-manager but then not disabling the functionality and just warn the user that there is not network-manager connection? That would remove the pain for users with my use case and still provide the same level of support for mainstream users.

It's not as if the successful check from network-manager would guarantee that there actually is a working network connection of that this connection would remain available for the duration of an update or installation.

The current behavior adds no real value but induces quite a lot of pain - at least for a small minority of users facing this particular situation. 

> That's why we have services like NetworkManager is to make sure we aren't implementing the same code in our apps and we have a canonical source of truth for things like network status.

As you correctly noticed, you have more than one service: systemd-networkd is also installed by default.

If you choose a canonical source of truth, I would suggest to pay more attention to the accuracy of that source. I don't know how network manager defines its own scope here, but it does not accurate report the *network status*, it reports the status of connections it manages. That is not the same.

Ping @cassidyjames
